export { default as About } from "./About.astro";
export { default as Contacts } from "./Contacts.astro";
export { default as Education } from "./Education.astro";
export { default as Experiences } from "./Experiences.astro";
export { default as Header } from "./Header.astro";
export { default as Loading } from "./LoadScreen.astro";
export { default as Navbar } from "./Navbar";
export { default as Projects } from "./Projects.astro";
export { default as Skills } from "./Skills.astro";
